# Generated by Django 4.1.4 on 2023-01-30 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("caracteristiques", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Personne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("prenom", models.CharField(max_length=100)),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        choices=[("F", "Féminin"), ("M", "Masculin")],
                        max_length=1,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Auteur",
            fields=[
                (
                    "personne_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bibliotheque.personne",
                    ),
                ),
                ("date_naissance", models.DateField(null=True)),
                ("date_mort", models.DateField(null=True)),
                ("lieu_naissance", models.CharField(max_length=200)),
                (
                    "conjoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conjoint_rn",
                        to="bibliotheque.personne",
                    ),
                ),
                (
                    "mere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enfant_mere",
                        to="bibliotheque.personne",
                    ),
                ),
                (
                    "pere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enfant_pere",
                        to="bibliotheque.personne",
                    ),
                ),
            ],
            bases=("bibliotheque.personne",),
        ),
        migrations.CreateModel(
            name="Livre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                (
                    "courant",
                    models.ManyToManyField(blank=True, to="bibliotheque.courant"),
                ),
                (
                    "auteur",
                    models.ManyToManyField(blank=True, to="bibliotheque.auteur"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FaitHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date_debut", models.DateField(null=True)),
                ("date_fin", models.DateField(null=True)),
                (
                    "auteur",
                    models.ManyToManyField(blank=True, to="bibliotheque.auteur"),
                ),
            ],
            options={
                "verbose_name_plural": "Faits Historiques",
            },
        ),
    ]
