# Generated by Django 4.1.4 on 2023-01-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='auteur',
        ),
        migrations.AddField(
            model_name='livre',
            name='auteur',
            field=models.ManyToManyField(blank=True, to='bibliotheque.auteur'),
        ),
    ]
