# Generated by Django 4.1.4 on 2023-02-19 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bibliotheque", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auteur",
            name="conjoint",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conjoint_rn",
                to="bibliotheque.personne",
            ),
        ),
        migrations.CreateModel(
            name="Edition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.DateField(null=True)),
                ("langue", models.CharField(max_length=200)),
                ("ville", models.CharField(max_length=200)),
                ("pays", models.CharField(max_length=200)),
                ("editeur", models.CharField(max_length=200)),
                ("imprimerie", models.CharField(max_length=200)),
                (
                    "livre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bibliotheque.livre",
                    ),
                ),
            ],
        ),
    ]
