# Generated by Django 4.1.4 on 2023-02-19 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bibliotheque", "0002_alter_auteur_conjoint_edition"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courant",
            old_name="titre",
            new_name="nom",
        ),
        migrations.RemoveField(
            model_name="auteur",
            name="conjoint",
        ),
        migrations.RemoveField(
            model_name="auteur",
            name="mere",
        ),
        migrations.RemoveField(
            model_name="auteur",
            name="pere",
        ),
        migrations.AddField(
            model_name="personne",
            name="amis",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="conjoint_rn",
                to="bibliotheque.personne",
            ),
        ),
        migrations.AddField(
            model_name="personne",
            name="conjoint",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conjoint_rn",
                to="bibliotheque.personne",
            ),
        ),
        migrations.AddField(
            model_name="personne",
            name="mere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enfants_mere",
                to="bibliotheque.personne",
            ),
        ),
        migrations.AddField(
            model_name="personne",
            name="pere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enfants_pere",
                to="bibliotheque.personne",
            ),
        ),
    ]
