# Generated by Django 4.1.4 on 2023-02-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bibliotheque",
            "0003_rename_titre_courant_nom_remove_auteur_conjoint_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("caracteristiques", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="personne",
            name="amis",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="ami_rn", to="bibliotheque.personne"
            ),
        ),
        migrations.AlterField(
            model_name="personne",
            name="genre",
            field=models.CharField(
                blank=True,
                choices=[("F", "Féminin"), ("M", "Masculin"), ("A", "Autre")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="livre",
            name="genre",
            field=models.ManyToManyField(blank=True, to="bibliotheque.genre"),
        ),
    ]
