# Generated by Django 4.1.4 on 2023-02-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bibliotheque",
            "0004_genre_alter_personne_amis_alter_personne_genre_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FaitMarquant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("date_debut", models.DateField(null=True)),
                ("date_fin", models.DateField(null=True)),
            ],
            options={
                "verbose_name_plural": "Faits Marquants",
            },
        ),
        migrations.RenameModel(
            old_name="FaitHistorique",
            new_name="FaitSocial",
        ),
        migrations.AlterModelOptions(
            name="faitsocial",
            options={"verbose_name_plural": "Faits Sociaux"},
        ),
        migrations.AddField(
            model_name="auteur",
            name="faitmarquant",
            field=models.ManyToManyField(blank=True, to="bibliotheque.faitmarquant"),
        ),
    ]
