# Generated by Django 4.1.4 on 2023-02-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibliotheque", "0006_alter_personne_amis"),
    ]

    operations = [
        migrations.AddField(
            model_name="personne",
            name="secondaire",
            field=models.ManyToManyField(blank=True, to="bibliotheque.personne"),
        ),
    ]
