# Generated by Django 4.1.4 on 2023-02-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bibliotheque", "0007_personne_secondaire"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personne",
            name="conjoint",
        ),
        migrations.CreateModel(
            name="RelationConjoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "c1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conjoint1_rn",
                        to="bibliotheque.personne",
                    ),
                ),
                (
                    "c2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conjoint2_rn",
                        to="bibliotheque.personne",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="personne",
            name="conjoint",
            field=models.ManyToManyField(
                through="bibliotheque.RelationConjoint", to="bibliotheque.personne"
            ),
        ),
    ]
